title: Résumé
baseurl: "/resume/"
color: grape
exclude:
  - _README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
  - Rakefile
